version: "3.8"

services:
  photo-manager:
    image: ghcr.io/cloonix/photo-manager:latest
    ports:
      - "8000:8000"
    volumes:
      - ${LOCAL_PHOTOS}:/photos:rw # Host photos directory
      - ${LOCAL_DATA}:/app/data # Persistent metadata & cache
    restart: unless-stopped
    env_file: .env
